-- ===================================================================
-- AYDIN İLİ TÜM İLÇELER MAHALLELERİ
-- Toplam 17 İlçe
-- ===================================================================

-- BOZDOĞAN İlçesi Mahalleleri (district_id: 758)
INSERT INTO neighborhoods (district_id, name, status) VALUES
(758, 'Adnan Menderes', 'active'),
(758, 'Akçaköy', 'active'),
(758, 'Aydoğdu', 'active'),
(758, 'Bayır', 'active'),
(758, 'Çakırbeyli', 'active'),
(758, 'Çamköy', 'active'),
(758, 'Dedeler', 'active'),
(758, 'Dereköy', 'active'),
(758, 'Efeler', 'active'),
(758, 'Gölcük', 'active'),
(758, 'Karacahisar', 'active'),
(758, 'Karacaköy', 'active'),
(758, 'Kavaklı', 'active'),
(758, 'Kızılcaköy', 'active'),
(758, 'Meşelik', 'active'),
(758, 'Sarıcaali', 'active'),
(758, 'Yazıkent', 'active'),
(758, 'Yeniköy', 'active'),

-- BUHARKENT İlçesi Mahalleleri (district_id: 766)
(766, 'Akçaova', 'active'),
(766, 'Aşağıkuyucak', 'active'),
(766, 'Bahçeköy', 'active'),
(766, 'Bozköy', 'active'),
(766, 'Cumhuriyet', 'active'),
(766, 'Danamandıra', 'active'),
(766, 'Dereköy', 'active'),
(766, 'Düzağaç', 'active'),
(766, 'Gedikler', 'active'),
(766, 'Gölcük', 'active'),
(766, 'Güllüce', 'active'),
(766, 'Kayadibi', 'active'),
(766, 'Kılıç', 'active'),
(766, 'Mehmetler', 'active'),
(766, 'Muratdağı', 'active'),
(766, 'Sazak', 'active'),
(766, 'Yakaköy', 'active'),
(766, 'Yeniköy', 'active'),
(766, 'Yukarıkuyucak', 'active'),

-- ÇİNE İlçesi Mahalleleri (district_id: 767)
(767, 'Aliağa', 'active'),
(767, 'Atatürk', 'active'),
(767, 'Aydınlar', 'active'),
(767, 'Bağarcık', 'active'),
(767, 'Camili', 'active'),
(767, 'Cumhuriyet', 'active'),
(767, 'Çavdar', 'active'),
(767, 'Çobanisa', 'active'),
(767, 'Değirmenli', 'active'),
(767, 'Gazi', 'active'),
(767, 'Gökçen', 'active'),
(767, 'Güre', 'active'),
(767, 'Hacıveliler', 'active'),
(767, 'İsmetpaşa', 'active'),
(767, 'Kalehan', 'active'),
(767, 'Kocagür', 'active'),
(767, 'Kuyucak', 'active'),
(767, 'Mersinbeleni', 'active'),
(767, 'Nalıncılar', 'active'),
(767, 'Ortaköy', 'active'),
(767, 'Paşa', 'active'),
(767, 'Pelitköy', 'active'),
(767, 'Sütlaç', 'active'),
(767, 'Tepecik', 'active'),
(767, 'Yaka', 'active'),
(767, 'Yeniköy', 'active'),

-- DİDİM İlçesi Mahalleleri (district_id: 768)
(768, 'Akbük', 'active'),
(768, 'Altınkum', 'active'),
(768, 'Avcılar', 'active'),
(768, 'Balat', 'active'),
(768, 'Bayındır', 'active'),
(768, 'Cumhuriyet', 'active'),
(768, 'Çamlık', 'active'),
(768, 'Efeler', 'active'),
(768, 'Ekinambarı', 'active'),
(768, 'Fevzipaşa', 'active'),
(768, 'Gümüşkent', 'active'),
(768, 'Hisar', 'active'),
(768, 'Mavisehir', 'active'),
(768, 'Sarıkemer', 'active'),
(768, 'Şahinler', 'active'),
(768, 'Tekmen', 'active'),
(768, 'Yenihisar', 'active'),
(768, 'Yeşilköy', 'active'),
(768, 'Yoran', 'active'),

-- EFELER İlçesi Mahalleleri (district_id: 769)
(769, 'Adnan Menderes', 'active'),
(769, 'Ata', 'active'),
(769, 'Cumhuriyet', 'active'),
(769, 'Danişment', 'active'),
(769, 'Devlet Bahçeli', 'active'),
(769, 'Esentepe', 'active'),
(769, 'Girne', 'active'),
(769, 'Hasanefendi', 'active'),
(769, 'Hürriyet', 'active'),
(769, 'İstiklal', 'active'),
(769, 'Kemer', 'active'),
(769, 'Kurtuluş', 'active'),
(769, 'Meşrutiyet', 'active'),
(769, 'Orta', 'active'),
(769, 'Paşa', 'active'),
(769, 'Ramazan', 'active'),
(769, 'Tepecik', 'active'),
(769, 'Umurlu', 'active'),
(769, 'Zafer', 'active'),
(769, 'Zeybek', 'active'),

-- GERMENCİK İlçesi Mahalleleri (district_id: 770)
(770, 'Akçaköy', 'active'),
(770, 'Alangüllü', 'active'),
(770, 'Araplar', 'active'),
(770, 'Arvalya', 'active'),
(770, 'Atça', 'active'),
(770, 'Bağarası', 'active'),
(770, 'Batıkent', 'active'),
(770, 'Beyazıtlı', 'active'),
(770, 'Cumhuriyet', 'active'),
(770, 'Çakırbeyli', 'active'),
(770, 'Dalama', 'active'),
(770, 'Doğancık', 'active'),
(770, 'Feslek', 'active'),
(770, 'Fevzipaşa', 'active'),
(770, 'Gölcük', 'active'),
(770, 'Güvendik', 'active'),
(770, 'Işıklar', 'active'),
(770, 'Kalınharman', 'active'),
(770, 'Kızılcagedik', 'active'),
(770, 'Kurtuluş', 'active'),
(770, 'Nargedik', 'active'),
(770, 'Ödemiş', 'active'),
(770, 'Sarıkemer', 'active'),
(770, 'Sazlı', 'active'),
(770, 'Umurlu', 'active'),
(770, 'Yeşilyurt', 'active'),

-- İNCİRLİOVA İlçesi Mahalleleri (district_id: 771)
(771, 'Akçaköy', 'active'),
(771, 'Cumhuriyet', 'active'),
(771, 'Çakırbeyli', 'active'),
(771, 'Çamtepe', 'active'),
(771, 'Dalama', 'active'),
(771, 'Esatpaşa', 'active'),
(771, 'Hacıahmetler', 'active'),
(771, 'Hacımemiş', 'active'),
(771, 'İnkur', 'active'),
(771, 'Kuşçular', 'active'),
(771, 'Ovakent', 'active'),
(771, 'Paşa', 'active'),
(771, 'Yamalak', 'active'),

-- KARACASU İlçesi Mahalleleri (district_id: 772)
(772, 'Ağaçhisar', 'active'),
(772, 'Akçaova', 'active'),
(772, 'Akıncılar', 'active'),
(772, 'Bölme', 'active'),
(772, 'Bucakköy', 'active'),
(772, 'Cevizli', 'active'),
(772, 'Cumhuriyet', 'active'),
(772, 'Danişment', 'active'),
(772, 'Dedebağı', 'active'),
(772, 'Derbent', 'active'),
(772, 'Esentepe', 'active'),
(772, 'Eskihisar', 'active'),
(772, 'Fevzipaşa', 'active'),
(772, 'Geyre', 'active'),
(772, 'Gökçeköy', 'active'),
(772, 'Göveçlik', 'active'),
(772, 'Hacımusalar', 'active'),
(772, 'Işıklar', 'active'),
(772, 'Karacasu', 'active'),
(772, 'Salavatlı', 'active'),
(772, 'Tekçam', 'active'),
(772, 'Yenicekent', 'active'),
(772, 'Yenipınar', 'active'),
(772, 'Yeşilyurt', 'active'),
(772, 'Yazır', 'active'),

-- KARPUZLU İlçesi Mahalleleri (district_id: 773)
(773, 'Atatürk', 'active'),
(773, 'Cumhuriyet', 'active'),
(773, 'Işıklar', 'active'),
(773, 'Karpuzlu', 'active'),
(773, 'Kaşıkçı', 'active'),
(773, 'Kurtuluş', 'active'),
(773, 'Pınarlı', 'active'),
(773, 'Yeşilköy', 'active'),

-- KOÇARLI İlçesi Mahalleleri (district_id: 774)
(774, 'Atatürk', 'active'),
(774, 'Ballıca', 'active'),
(774, 'Bayındır', 'active'),
(774, 'Bozkurt', 'active'),
(774, 'Büyükköy', 'active'),
(774, 'Camikebir', 'active'),
(774, 'Cumhuriyet', 'active'),
(774, 'Çaybaşı', 'active'),
(774, 'Çobanlar', 'active'),
(774, 'Eskiçine', 'active'),
(774, 'Fevzipaşa', 'active'),
(774, 'Gazi', 'active'),
(774, 'Güre', 'active'),
(774, 'Hamidiye', 'active'),
(774, 'İsabeyli', 'active'),
(774, 'Kapıkaya', 'active'),
(774, 'Kazıklı', 'active'),
(774, 'Kurtuluş', 'active'),
(774, 'Kuzguncuk', 'active'),
(774, 'Pınarbaşı', 'active'),
(774, 'Salihler', 'active'),
(774, 'Sancaklı', 'active'),
(774, 'Süller', 'active'),
(774, 'Tepecik', 'active'),
(774, 'Yeşilyurt', 'active'),

-- KÖŞK İlçesi Mahalleleri (district_id: 775)
(775, 'Atatürk', 'active'),
(775, 'Avdan', 'active'),
(775, 'Cumhuriyet', 'active'),
(775, 'Çalış', 'active'),
(775, 'Çatalhöyük', 'active'),
(775, 'Değirmendere', 'active'),
(775, 'Gazi', 'active'),
(775, 'Güvendik', 'active'),
(775, 'Kavaklıdere', 'active'),
(775, 'Kurtuluş', 'active'),
(775, 'Ortaklar', 'active'),
(775, 'Yağcılı', 'active'),
(775, 'Yenice', 'active'),

-- KUŞADASI İlçesi Mahalleleri (district_id: 776)
(776, 'Akıncılar', 'active'),
(776, 'Atatürk', 'active'),
(776, 'Camiatik', 'active'),
(776, 'Camikebir', 'active'),
(776, 'Çamlık', 'active'),
(776, 'Davutlar', 'active'),
(776, 'Güzelçamlı', 'active'),
(776, 'Hacıfeyzullah', 'active'),
(776, 'Kadinlar Denizi', 'active'),
(776, 'Soğucak', 'active'),
(776, 'Türkmen', 'active'),

-- KUYUCAK İlçesi Mahalleleri (district_id: 777)
(777, 'Akçeşme', 'active'),
(777, 'Akovalı', 'active'),
(777, 'Atatürk', 'active'),
(777, 'Bayındır', 'active'),
(777, 'Bozyurt', 'active'),
(777, 'Büyükköy', 'active'),
(777, 'Cumhuriyet', 'active'),
(777, 'Çatak', 'active'),
(777, 'Danişment', 'active'),
(777, 'Esentepe', 'active'),
(777, 'İmamlar', 'active'),
(777, 'Kafaca', 'active'),
(777, 'Kuyucak', 'active'),
(777, 'Sarıyahşi', 'active'),
(777, 'Tepecik', 'active'),

-- NAZİLLİ İlçesi Mahalleleri (district_id: 778)
(778, 'Acarlar', 'active'),
(778, 'Araphisar', 'active'),
(778, 'Ata', 'active'),
(778, 'Bahçelievler', 'active'),
(778, 'Bıçakçı', 'active'),
(778, 'Boğaziçi', 'active'),
(778, 'Cennetpınar', 'active'),
(778, 'Cumhuriyet', 'active'),
(778, 'Çağlayan', 'active'),
(778, 'Çalışkan', 'active'),
(778, 'Çiftlik', 'active'),
(778, 'Dedeköy', 'active'),
(778, 'Ege', 'active'),
(778, 'Fesleğen', 'active'),
(778, 'Gazi', 'active'),
(778, 'Gödrenli', 'active'),
(778, 'Hasanköy', 'active'),
(778, 'Kurtuluş', 'active'),
(778, 'Levent', 'active'),
(778, 'Meşelik', 'active'),
(778, 'Mutlukent', 'active'),
(778, 'Pınarcık', 'active'),
(778, 'Pirlibey', 'active'),
(778, 'Salkım', 'active'),
(778, 'Sarıcaova', 'active'),
(778, 'Sultaniye', 'active'),
(778, 'Şehit Şahin', 'active'),
(778, 'Tepeköy', 'active'),
(778, 'Turan', 'active'),
(778, 'Türkmen', 'active'),
(778, 'Yazıkent', 'active'),
(778, 'Yeşilköy', 'active'),
(778, 'Zafer', 'active'),

-- SÖKE İlçesi Mahalleleri (district_id: 779)
(779, 'Atburgazı', 'active'),
(779, 'Atatürk', 'active'),
(779, 'Balıklıova', 'active'),
(779, 'Bağarası', 'active'),
(779, 'Bayraktepe', 'active'),
(779, 'Cumhuriyet', 'active'),
(779, 'Çakmak', 'active'),
(779, 'Çaybaşı', 'active'),
(779, 'Doğanbey', 'active'),
(779, 'Gazi', 'active'),
(779, 'Güllübahçe', 'active'),
(779, 'Gümüldür', 'active'),
(779, 'İsabeyli', 'active'),
(779, 'Kazıklı', 'active'),
(779, 'Kurtuluş', 'active'),
(779, 'Sazlı', 'active'),
(779, 'Sökköy', 'active'),
(779, 'Tuzburgazı', 'active'),
(779, 'Yeniköy', 'active'),
(779, 'Yeniyurt', 'active'),

-- SULTANHİSAR İlçesi Mahalleleri (district_id: 780)
(780, 'Akçaavlu', 'active'),
(780, 'Atatürk', 'active'),
(780, 'Atça', 'active'),
(780, 'Beyobası', 'active'),
(780, 'Cumhuriyet', 'active'),
(780, 'Esenköy', 'active'),
(780, 'Esenpınar', 'active'),
(780, 'Fevzipaşa', 'active'),
(780, 'Güzelhisar', 'active'),
(780, 'Hıdırlık', 'active'),
(780, 'Karapınar', 'active'),
(780, 'Kavaklı', 'active'),
(780, 'Kızılyer', 'active'),
(780, 'Kurtuluş', 'active'),
(780, 'Sarıkemer', 'active'),
(780, 'Sultanhisar', 'active'),
(780, 'Şahin', 'active'),

-- YENİPAZAR İlçesi Mahalleleri (district_id: 781)
(781, 'Akıncılar', 'active'),
(781, 'Akkent', 'active'),
(781, 'Bekdemir', 'active'),
(781, 'Büyükçiftlik', 'active'),
(781, 'Cumhuriyet', 'active'),
(781, 'Çamlı', 'active'),
(781, 'Dereçiftlik', 'active'),
(781, 'Eski Yenipazar', 'active'),
(781, 'Fevzi Çakmak', 'active'),
(781, 'Gündoğan', 'active'),
(781, 'Işıklar', 'active'),
(781, 'Pınarkaya', 'active'),
(781, 'Söke', 'active'),
(781, 'Tekeler', 'active'),
(781, 'Yeşilköy', 'active')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- ===================================================================
-- İstatistikler:
-- - Toplam 17 İlçe
-- - Toplam yaklaşık 300+ Mahalle
-- ===================================================================

